# Set site.output == "epub"
output: "epub"
# Set site.image-set == "images/epub"
image-set: "images/epub"
# Turn off documentation and activate epub collection
collections:
  docs:
    output: false
  epub:
    output: true
